#ifndef PARSER_H
#define PARSER_H

#include "Alloc.h"
#include "Scan.h"
#include "Shared.h" 
 
typedef struct {
    char exposed : 1;
    char private : 1;
} varflags_t;

// externals are callbacks to functions defined by the vm (implementation specific).
// for example, some vm may support dynamic linking, ffi etc
typedef struct {
    type_t* type;
    char* name;
    
    varflags_t flags;
    uint16_t pid;
    uint16_t id;
} external_t; 

// metadata entry
typedef struct {
    char* name;
    metadata_t data;
} metainfo_t;
 
typedef struct {
    // having arenas simplifies the allocation/cleanup process a lot.
    // 99% of things in this language are needed until the very end of compilation.
    // the only downside could be alignment issues but unless that becomes a real problem, this is perfectly cool.
    arena_t consts;
    arena_t functs;
    arena_t types;
    arena_t typedefs;
    arena_t externals;
    arena_t other;
    arena_t meta;

    // do not change
    struct {
        uint16_t snum;  // number of function signatures
        uint16_t typec; // number of type entries
        uint16_t pnum;  // number of parsers
    };
} rootparser_t;

// one parser instance per file, all instances are compiled together using rootparser_t.
// hidden indices are used to ignore previously declared entries such as constants/typedefs/externals etc.
typedef struct parser_t {
    uint16_t hidden_consts;
    uint16_t hidden_typedefs;
    uint16_t hidden_externals;

    scanner_t scan;

    heapstr_t filepath;
    uint16_t diridx; // index in the filepath where the directory ends (essentially the last '/')
    uint16_t pid;    // parser uid

    rootparser_t* root;
} parser_t; 

typedef struct {
    int error; // 0 for success, 1 for failure (does not act as an errorcode)
    heapbuf_t bytecode; // heap allocated buffer containing the generated bytecode
} compile_output_t;

// allocates a new empty const (pid is set automatically).
void* parser_addconst(parser_t* parser);
// allocates a new empty function.
void* parser_addfunct(parser_t* parser);
// allocates a new empty typedef (pid is set automatically).
void* parser_addtypedef(parser_t* parser);
// allocates a new empty metadata entry.
void* parser_addmeta(parser_t* parser);
// allocates a new extern entry (pid is set automatically).
void* parser_addextern(parser_t* parser); 
// allocates some memory (memory is freed automatically when the compilation process is complete).
void* parser_alloc(parser_t* parser, size_t size);
// copies a strcut into the parser's internal memory as a null terminated string (used to increase the lifetime of the strcut).
char* parser_copycut(parser_t* parser, strcut_t cut);
// returns if the parser is the root parser
int parser_isroot(parser_t* parser);

// skips to the next semicolon (;) which in this language, indicates the end of any statement.
void parser_skip_statement(parser_t* parser);

//`path` is a heap allocated string thats freed when the compilation is complete. 
compile_output_t parser_compile(heapstr_t path, parser_t* parent);

// generates the bytecode of the root parser.
// used automatically after calling parser_compile if there are no errors.
heapbuf_t parser_genbytecode(rootparser_t* root);
#endif
